### PR TITLE
update roamjs-components to 0.80.3

### PR DESCRIPTION
**Pull request by mdroidian**
I do not have access to this repo to check for repo secrets @dvargas92495

### CODE REVIEW

**Comment by mdroidian** [comment]
Also, there was an issue with testing this one.  I'll discuss that with you today.

**Comment by mdroidian** [comment]
tested with `API_URL`

While it worked, I got the following console errors:

image

The first two also happen with the current Roam Depot version, but the second two do not.

**Comment by dvargasfuertes** [comment]
first two is expected, I am pushing out a fix to the bottom two now

**Comment by dvargasfuertes** [comment]
hey @mdroidian, I'm going to take over this branch - there are some backend redirecting that I want to group with this change

**Comment by dvargasfuertes** [comment]
Actually going to merge it into another branch that isn't main that I'm working off of

**Comment by mdroidian** [comment]
> Actually going to merge it into another branch that isn't main that I'm working off of

I noticed these changes haven't made it into main yet.  Are you still working on them locally?

**Comment by dvargasfuertes** [comment]
agh this slipped - feel free to take it over

**Pull request merged**
